Cosmetics

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -207,9 +207,9 @@ else
 fi
 
 
-log_echo "checking for libfftw3f..."
-if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "fftw3.h" "fftwf_init_threads();" ; then
-    log_echo "error: libfftw3f checking failed."
+log_echo "checking for fftw3f..."
+if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "fftw3.h" "fftwf_free(nullptr);" ; then
+    log_echo "error: fftw3f checking failed."
     error_exit "fftw3.h might not be installed or some libs missing."
 fi
 
