Normalize configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4,6 +4,8 @@
 #  configure script for VapourSynth-DFTTest
 #----------------------------------------------------------------------------
 
+## This script was modified based on d2vsource/configure.
+
 # -- help -------------------------------------------------------------------
 if test x"$1" = x"-h" -o x"$1" = x"--help" ; then
 cat << EOF
@@ -92,7 +94,6 @@ CXXFLAGS="-std=c++11 -Wall -I. -I$SRCDIR/include"
 LDFLAGS=""
 SOFLAGS="-shared"
 DEPLIBS="fftw3f"
-
 TARGET="-msse2"
 SIMD="-DVS_TARGET_CPU_X86"
 
@@ -204,6 +205,16 @@ else
     log_echo "warning: pkg-config or pc files not found, lib detection may be inaccurate."
 fi
 
+log_echo "checking for vapoursynth headers..."
+if $PKGCONFIGBIN --exists vapoursynth 2> /dev/null; then
+    VSCFLAGS="$($PKGCONFIGBIN --cflags vapoursynth)"
+else
+    log_echo "warning: pkg-config or pc files not found, header detection may be inaccurate."
+fi
+if ! cc_check "$CXXFLAGS $VSCFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
+    log_echo "error: vapoursynth checking failed."
+    error_exit "VapourSynth.h might not be installed."
+fi
 
 log_echo "checking for fftw3f..."
 if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "fftw3.h" "fftwf_free(nullptr);" ; then
@@ -213,6 +224,7 @@ fi
 
 LDFLAGS="$SOFLAGS $LDFLAGS"
 LIBS="$LIBS $XLIBS"
+CXXFLAGS="$CXXFLAGS $VSCFLAGS"
 
 
 cat >> config.mak << EOF
