Do libs checking before VS header checking

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -205,6 +205,12 @@ else
 fi
 
 
+log_echo "checking for fftw3f..."
+if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "fftw3.h" "fftwf_free(nullptr);" ; then
+    log_echo "error: fftw3f checking failed."
+    error_exit "fftw3.h might not be installed or some libs missing."
+fi
+
 log_echo "checking for vapoursynth headers..."
 if $PKGCONFIGBIN --exists vapoursynth 2> /dev/null; then
     CXXFLAGS="$CXXFLAGS $($PKGCONFIGBIN --cflags vapoursynth)"
@@ -214,12 +220,6 @@ fi
 if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "VapourSynth.h" "getVapourSynthAPI;" ; then
     log_echo "error: vapoursynth checking failed."
     error_exit "VapourSynth.h might not be installed."
-fi
-
-log_echo "checking for fftw3f..."
-if ! cc_check "$CXXFLAGS" "$LDFLAGS $LIBS $XLIBS" "fftw3.h" "fftwf_free(nullptr);" ; then
-    log_echo "error: fftw3f checking failed."
-    error_exit "fftw3.h might not be installed or some libs missing."
 fi
 
 LDFLAGS="$SOFLAGS $LDFLAGS"
